.

diff --git a/.github/workflows/deploy-pipeline.yml b/.github/workflows/deploy-pipeline.yml
--- a/.github/workflows/deploy-pipeline.yml
+++ b/.github/workflows/deploy-pipeline.yml
@@ -1,34 +1,78 @@
+# name: Pipeline success Deployment failure
+
+# on:
+#   push:
+#     paths: 
+#       - '04-deployment-success-but-app-down/**'
+#     branches: 
+#       - main
+#       - dev
+
+# jobs:
+#   deployment-fail-check-jobs:
+#     runs-on: self-hosted
+#     defaults:
+#       run: 
+#         working-directory: 04-deployment-success-but-app-down
+    
+#     steps:
+#       - name: checkout repo
+#         uses: actions/checkout@v4
+      
+#       - name: build image
+#         run: docker build -t test-img .
+
+#       - name: run img in container
+#         run: docker run -d -p 5000:5000 --name prod-container test-img
+
+#       - name: tesing happens
+#         run: echo test successful
+
+#       - name: destroy resource
+#         if : always()
+#         run: docker stop prod-container && docker rm prod-container
+
+
 name: Pipeline success Deployment failure
 
 on:
   push:
-    paths: 
+    paths:
       - '04-deployment-success-but-app-down/**'
-    branches: 
+    branches:
       - main
       - dev
 
 jobs:
   deployment-fail-check-jobs:
     runs-on: self-hosted
+
     defaults:
-      run: 
+      run:
         working-directory: 04-deployment-success-but-app-down
-    
+
     steps:
       - name: checkout repo
         uses: actions/checkout@v4
-      
+
+      - name: cleanup old container
+        run: |
+          docker stop prod-container || true
+          docker rm prod-container || true
+
       - name: build image
         run: docker build -t test-img .
 
       - name: run img in container
         run: docker run -d -p 5000:5000 --name prod-container test-img
-        
-      - name: tesing happens
-        run: echo test successful
+
+      - name: test app
+        run: |
+          sleep 5
+          curl http://localhost:5000
 
       - name: destroy resource
-        if : always()
-        run: docker stop prod-container && docker rm prod-container
-
+        if: always()
+        run: |
+          docker stop prod-container || true
+          docker rm prod-container || true
