masks the env vars

diff --git a/.github/workflows/security-pipeline.yml b/.github/workflows/security-pipeline.yml
--- a/.github/workflows/security-pipeline.yml
+++ b/.github/workflows/security-pipeline.yml
@@ -1,52 +1,91 @@
-name: CI Security Pipeline
+# name: CI Security Pipeline
+
+# on:
+#   push:
+#     paths: 
+#       - '03-security-and-secrets/**'
+#     branches:
+#       - main
+#       - dev
+
+# jobs:
+#   build-test-securitycheck:
+#     runs-on: ubuntu-latest
+#     defaults:
+#       run: 
+#         working-directory: 03-security-and-secrets
+#     env:
+#       API_KEY: ${{ secrets.API_KEY }}   
+#     steps:
+#       - name: checkouting repo
+#         uses: actions/checkout@v4
+      
+#       - name: building it as image
+#         run: docker build -t build-image .
+      
+#       - name: run the docker image in the container
+#         run: docker run -d -p 5000:5000 -e API_KEY=$API_KEY --name prod-container build-image
+      
+#       - name: display the logs
+#         run: docker logs prod-container
+      
+#       - name: check app is alive or not
+#         run : |
+#           for i in {1..10}; do
+#             if curl -s http://localhost:5000; then
+#               echo "app is live"
+#               exit 0
+#             else
+#               echo "app is down need attention"
+#               sleep 2
+#             fi
+#           done
+
+#           echo "failed to start"
+#           exit 1
+          
+#       - name: second check
+#         run: curl -f http://localhost:5000
+
+#       - name: destroy resources
+#         if : always()
+#         run: docker stop prod-container && docker rm prod-container
+
+
+name: Security-CI-Pipeline
 
 on:
   push:
-    paths: 
+    paths:
       - '03-security-and-secrets/**'
     branches:
       - main
-      - dev
 
 jobs:
-  build-test-securitycheck:
-    runs-on: ubuntu-latest
+  dummy-security-check:
+    runs-on:
+      - ubuntu-latest
     defaults:
       run: 
-        working-directory: 03-security-and-secrets
+        working-directory: '03-security-and-secrets/**'
+    
     env:
-      API_KEY: ${{ secrets.API_KEY }}   
+      API_KEY : ${{ secrets.API_KEY }}
+
     steps:
-      - name: checkouting repo
+      - name: checkout repo
         uses: actions/checkout@v4
-      
-      - name: building it as image
-        run: docker build -t build-image .
-      
-      - name: run the docker image in the container
-        run: docker run -d -p 5000:5000 -e API_KEY=$API_KEY --name prod-container build-image
-      
-      - name: display the logs
-        run: docker logs prod-container
-      
-      - name: check app is alive or not
-        run : |
-          for i in {1..10}; do
-            if curl -s http://localhost:5000; then
-              echo "app is live"
-              exit 0
-            else
-              echo "app is down need attention"
-              sleep 2
-            fi
-          done
 
-          echo "failed to start"
-          exit 1
-          
-      - name: second check
-        run: curl -f http://localhost:5000
+      - name: build docker image
+        run: docker build -t test-img .
+      
+      - name: run container with img
+        run: docker run -d -p 5000:5000 --name prod-container
+      
+      - name: show docker logs
+        run: docker logs prod-containerx
 
-      - name: destroy resources
-        if : always()
-        run: docker stop prod-container && docker rm prod-container
+      - name: destroy container
+        run: docker stop prod-container && docker rm container prod-container
+
+
